apiVersion: "henrik.dk/v1"
kind: KongApi
metadata:
  name: petstore-pet-api
  namespace: petstore
spec:
  port: 8080
  swagger: /swagger.json
---
apiVersion: "henrik.dk/v1"
kind: KongApi
metadata:
  name: petstore-store-api
  namespace: petstore
spec:
  port: 8080
  swagger: /swagger.json
---
apiVersion: "henrik.dk/v1"
kind: KongApiData
metadata:
  name: petstore-pet-api
  namespace: petstore
spec:
  data: "wak wak"
  updated: "2020-01-21T21:01:02Z"
---
apiVersion: "henrik.dk/v1"
kind: KongApiConfig
metadata:
  name: api
  namespace: petstore
spec:
  title: "Test API"
  description: "A combined api of the entire system"
  termsUrl: "https://www.lawinsider.com/dictionary/url-terms"
  contactEmail: "spam@real.com"
  licenseName: "Apache 2.0"
  licenseUrl: "https://www.apache.org/licenses/LICENSE-2.0"
  securityScheme: "JWTBearer"
  securityKeyName: ""
