name: Release Components

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build Image
        run: docker build . --file Dockerfile --tag kong-portal-controller
        working-directory: Kong.Portal.Controller

      - name: Log In
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Push Image
        run: |
          build_id=$(date +'%Y%m%d')
          build_id+="-"
          build_id+=$(git rev-parse --short "$GITHUB_SHA")
          docker tag kong-portal-controller ${{ secrets.DOCKER_USER }}/kong-portal-controller:$build_id
          docker push ${{ secrets.DOCKER_USER }}/kong-portal-controller:$build_id
